### ISSUE TITLE
Error when omit "workers" index in the grid configuration

### ISSUE THREAD

**Issue by marcosnobrega** [abmargb/oursim-ext#17]
Grid configuration:

{  
    discoveryService: {id : "ds"},
    peers: [{id: "peerA", discoveryService: "ds", workers:[
                {id: "worker1A", cpu: "2"},
                {id: "worker2A", cpu: "1.5"},
                {id: "worker3A", cpu: "1.2"},
                {id: "worker4A", cpu: "1"},
                {id: "worker5A", cpu: "1.3"},
                {id: "worker6A", cpu: "1.5"}
                ]},
            {id: "peerB", discoveryService: "ds"}
            ],
    brokers: [{id: "broker1A", peer: "peerA"}, {id: "broker2A", peer: "peerA"}, {id: "broker1B", peer: "peerB"}]
}

Exception message:

Exception in thread "main" java.lang.IllegalArgumentException: org.json.JSONException: JSONObject["workers"] not found.
    at br.edu.ufcg.lsd.oursim.util.JSONUtils.getJSONArray(JSONUtils.java:37)
    at br.edu.ufcg.lsd.oursim.factories.DefaultGridFactory.createPeer(DefaultGridFactory.java:141)
    at br.edu.ufcg.lsd.oursim.factories.DefaultGridFactory.createGrid(DefaultGridFactory.java:61)
    at br.edu.ufcg.lsd.oursim.OurSim.<init>(OurSim.java:38)
    at br.edu.ufcg.lsd.oursim.Main.main(Main.java:25)
Caused by: org.json.JSONException: JSONObject["workers"] not found.
    at org.json.JSONObject.get(JSONObject.java:498)
    at org.json.JSONObject.getJSONArray(JSONObject.java:574)
    at br.edu.ufcg.lsd.oursim.util.JSONUtils.getJSONArray(JSONUtils.java:35)
    ... 4 more

**Comment by abmargb** [comment]
This is an expected error. Peer configuration should have a 'workers' array, even if this array is empty.
