### ISSUE TITLE
Error running with property "BROKER_MAX_REPLICAS" defined as 1

### ISSUE THREAD

**Issue by marcosnobrega** [abmargb/oursim-ext#18]
Grid configuration:

{  
    discoveryService: {id : "ds"},
    peers: [{id: "peerA", discoveryService: "ds", workers:[
                {id: "worker1A", cpu: "2"},
                {id: "worker2A", cpu: "1.5"},
                {id: "worker3A", cpu: "1.2"},
                {id: "worker4A", cpu: "1"},
                {id: "worker5A", cpu: "1.3"},
                {id: "worker6A", cpu: "1.5"}
                ]},
            {id: "peerB", discoveryService: "ds", workers:[]}
            ],
    brokers: [{id: "broker1A", peer: "peerA"}, {id: "broker2A", peer: "peerA"}, {id: "broker1B", peer: "peerB"}]
}

Events queue:

DS_UP       100     ds
WORKER_UP   300     worker1A
WORKER_UP   400     worker2A
WORKER_UP   400     worker3A
WORKER_UP   400     worker4A
WORKER_UP   400     worker5A
WORKER_UP   400     worker6A
BROKER_UP   500     broker1A
BROKER_UP   500     broker2A
BROKER_UP   500     broker1B
PEER_UP     800     peerA
PEER_UP     800     peerB
ADD_JOB     15000   broker1A {id:1 , tasks:[{duration:10000},{duration:1000}]}
ADD_JOB     100000  broker1B {id:1 , tasks:[{duration:10000},{duration:10000}]}
HALT        500000

Exception message

Exception in thread "main" java.lang.NullPointerException
    at br.edu.ufcg.lsd.oursim.events.peer.accounting.AccountingHelper.getAccountingsByProvider(AccountingHelper.java:53)
    at br.edu.ufcg.lsd.oursim.events.peer.accounting.AccountingHelper.commitReplicaAccountings(AccountingHelper.java:16)
    at br.edu.ufcg.lsd.oursim.events.peer.FinishRequestEvent.process(FinishRequestEvent.java:32)
    at br.edu.ufcg.lsd.oursim.OurSim.run(OurSim.java:65)
    at br.edu.ufcg.lsd.oursim.Main.main(Main.java:32)

**Comment by abmargb** [comment]
Fixed.
