### ISSUE TITLE
"NullPointer" in "RequestWorkersEvent" running with attached job and grid

### ISSUE THREAD

**Issue by marcosnobrega** [abmargb/oursim-ext#19]
Grid configuration

http://pastebin.com/YymVcCFk

Events configuration

http://pastebin.com/wsrpKWz8

Exception message:

Exception in thread "main" java.lang.NullPointerException
    at br.edu.ufcg.lsd.oursim.events.peer.RequestWorkersEvent.forwardRequestToCommunity(RequestWorkersEvent.java:64)
    at br.edu.ufcg.lsd.oursim.events.peer.RequestWorkersEvent.process(RequestWorkersEvent.java:52)
    at br.edu.ufcg.lsd.oursim.OurSim.run(OurSim.java:65)
    at br.edu.ufcg.lsd.oursim.Main.main(Main.java:30)

**Comment by marcosnobrega** [comment]
I changed the events order, changing the PEER_UP event to be done after DS_UP event, and now it works

**Comment by abmargb** [comment]
Fixed.
