### ISSUE TITLE
"NullPointer" in "AddJobEvent" when set the same time to "ADD_JOB" and "BROKER_UP" events

### ISSUE THREAD

**Issue by marcosnobrega** [abmargb/oursim-ext#21]
This error occurs when the time to set up the broker that requests the "add_job" is the same time in "add_job" event

Exception in thread "main" java.lang.NullPointerException
    at br.edu.ufcg.lsd.oursim.events.broker.AddJobEvent.process(AddJobEvent.java:34)
    at br.edu.ufcg.lsd.oursim.OurSim.run(OurSim.java:65)
    at br.edu.ufcg.lsd.oursim.Main.main(Main.java:31)

**Comment by abmargb** [comment]
Failure detection events and its secondary events should have a higher priority. 
To be fixed. 

Thanks for the report Marcos.
